services:
  bot:
    build: .
    container_name: mahalla_bot
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://mahalla_user:22446688l@localhost:5432/mahalla_bot_db
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - mahalla-network

  db:
    image: postgres:15-alpine
    container_name: mahalla_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mahalla_bot_db
      POSTGRES_USER: mahalla_user
      POSTGRES_PASSWORD: 22446688l
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - mahalla-network

volumes:
  postgres_data:

networks:
  mahalla-network:
    driver: bridge