services:
  - type: web
    name: mahalla-aloqa-boti
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: ALLOWED_GROUP_IDS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: mahalla-db
          property: connectionString
      - key: DEV_NAME
        value: Mahalla Developer
      - key: DEV_USERNAME
        value: "@dev_username"
      - key: BOT_USERNAME
        value: "@MahallaYordamBot"

databases:
  - name: mahalla-db
    databaseName: mahalla_bot_db
    plan: free